Feature/asp 7
ViktarDunayeu/VJV-Survey pull request #19
Opened 2021-01-03 09:09 UTC by julia018

Таска [ASP-7](https://andersenlaboratory.atlassian.net/browse/ASP-7).
LWC-компонента для второго скрина (создание trigger rules). Содержит кастомную flow-навигацию - при добавлении во flow нужно убрать галку с "Show Footer" секции "Configure Frame".
![Prompt](https://user-images.githubusercontent.com/35733535/103475170-ddc79600-4dbb-11eb-8c7e-3a92e362ea6f.png)

2021-01-03 21:51 UTC, DunaevViktor commented on .vscode/settings.json
>  }
что это за конфиг и нужен ли он всем?

2021-01-03 21:52 UTC, DunaevViktor commented on force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.auradoc
> +</aura:documentation>
файл заглушка - не нужен в pull request

2021-01-03 21:53 UTC, DunaevViktor commented on force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapper.svg
> +</svg>
так же бесполезный файл, созданный vs code по умолчанию, не нужен

2021-01-03 21:53 UTC, DunaevViktor commented on force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapperHelper.js
> +({});
бесполезная заглушка, не нужна в пр

2021-01-03 21:55 UTC, DunaevViktor commented on force-app/main/default/classes/MetadataFetcher.cls
> +
тут и далее очень странное форматирование, видимо это prettier? в будущем мы от него отказываемся и форматируем apex код так же, как это делает dev console

2021-01-03 22:00 UTC, DunaevViktor commented on force-app/main/default/globalValueSets/SurveyRuleObjects.globalValueSet-meta.xml
> +</GlobalValueSet>
у нас уже есть этот global set value в файле **Object_Api_Names.globalValueSet-meta.xml**
этот файл можно удалять

2021-01-03 22:01 UTC, DunaevViktor commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +</CustomLabels>
можно подробнее, что это за мета?

2021-01-03 22:01 UTC, DunaevViktor commented on force-app/main/default/objects/Trigger_Rule__c/Trigger_Rule__c.object-meta.xml
>      <enableActivities>false</enableActivities>
зачем?

2021-01-03 22:02 UTC, DunaevViktor commented on force-app/main/default/objects/Trigger_Rule__c/fields/Field_Name__c.field-meta.xml
> +
лишний file change

2021-01-04 06:00 UTC, julia018 commented on .vscode/settings.json
>  }
Авто-деплой на дефолтный орг при сохранении.

2021-01-04 06:11 UTC, julia018 commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +</CustomLabels>
Пояснение пользователю о том, что отправка опроса будет происходить при выполнении любого рула, а не всех (логика OR).
![PromptForUser](https://user-images.githubusercontent.com/35733535/103505905-7e758e80-4e6c-11eb-9c2b-4c9f5c44f8c3.png)

2021-01-04 07:03 UTC, Kiep13 requested changes

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapperController.js
> +    let triggerRules = event.getParam("triggerRules");
Я не знаю насколько это серьезная придирка, но в JS если ты не переиспользуешь переменную, ее принято объявлять как const, а не let.

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/aura/triggerRulesAuraWrapper/triggerRulesAuraWrapperController.js
> +    var navigate = cmp.get("v.navigateFlow");
Ключевое слово var сейчас почти моветон.Лучше использовать const.

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/classes/MetadataFetcher.cls
> +    // Get the object type of the SObject.
Комментарии остались

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/lwc/loadDataUtils/loadDataUtils.js
> +      // Remove null/undefined items
Комментарии

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
> +    super();
зачем здесь super?

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
> +      });
Очень нагруженный connectedCallback. Лучше разнести его содержимое в разные методы, а потом вызвать их здесь. Читаемость будет лучше.

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
> +    console.log(event.detail);
Я думаю, это сюда случайно попало

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
> +}
Пересмотри в этом файле еще раз на let и console.log, пожалуйста

2021-01-04 07:03 UTC, Kiep13 commented on force-app/main/default/lwc/triggerRulesWrapper/triggerRulesWrapper.js
> +}
Очень много лишних console log

2021-01-04 11:14 UTC, DunaevViktor commented on .vscode/settings.json
>  }
не думаю, что эта настройка нужна всем

2021-01-05 12:07 UTC, julia018 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.js
> +    super();
это required, без него никак

2021-01-05 13:14 UTC, Kiep13 commented on force-app/main/default/classes/LookupControllerTest.cls
> +    Contact testContact = new Contact(LastName = 'Happy New Year');
Это очень мило, но на будущее лучше так не делать)

2021-01-05 13:20 UTC, Kiep13 commented on force-app/main/default/lwc/customLookup/customLookup.html
> +                placeholder="Select an Option"
Select an Option - по идее тоже должен быть label (в develop уже есть такой)

2021-01-05 13:26 UTC, Kiep13 commented on force-app/main/default/lwc/customLookup/customLookup.html
> +                <span class="slds-assistive-text">Remove selected record</span>
Пропущен label

2021-01-05 13:26 UTC, Kiep13 commented on force-app/main/default/lwc/customLookup/customLookup.html
> +                <span class="slds-assistive-text">Remove selected record</span>
Можно взять delete label из develop ветки

2021-01-05 13:26 UTC, Kiep13 commented on force-app/main/default/lwc/customLookup/customLookup.html
> +                placeholder="Search..."
Label

2021-01-05 13:28 UTC, Kiep13 commented on force-app/main/default/lwc/customLookup/customLookup.js
> +          this.message = "No Records Found";
Полагаю тут тоже лучше label

2021-01-05 13:28 UTC, Kiep13 commented on force-app/main/default/lwc/loadDataUtils/loadDataUtils.js
> +      // Remove null/undefined items
Комментарии все еще тут?)

2021-01-05 13:29 UTC, Kiep13 commented on force-app/main/default/lwc/singleTriggerRule/helper.js
> +    label: "TRUE",
true и false можно попробовать взять с label ветки develop и потом просто каждую toUpperCase или toLowerCase

2021-01-05 13:30 UTC, Kiep13 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
> +    <!--Object-->
Коммент

2021-01-05 13:31 UTC, Kiep13 commented on force-app/main/default/lwc/triggerRulesFooterNavigation/triggerRulesFooterNavigation.html
> +      label="Next"
Label можно взять с develop ветки

2021-01-05 13:32 UTC, julia018 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
> +    <!--Object-->
этот коммент для читаемости в разметке

2021-01-05 13:32 UTC, julia018 commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
> +    <!--Object-->
комменты вообще запрещены?

2021-01-05 13:38 UTC, DunaevViktor commented on .prettierignore
> -coverage/
зачем?

2021-01-05 13:38 UTC, DunaevViktor commented on .prettierrc
> -}
зачем? нина настроила конфиги, эти пусть пока лежат

2021-01-05 13:40 UTC, DunaevViktor commented on package.json
>      "**/{aura|lwc}/**": [
тут линт вроде не связан с преттиер?

2021-01-05 13:42 UTC, DunaevViktor commented
Кстати, если ты где то юзала что то из этой меты **SurveyRuleObjects.globalValueSet-meta.xml**, например имя глобал сета и тд, то нужно не забыть сменить на имена и мету из **Object_Api_Names.globalValueSet-meta.xml**
я не нашел таких мест, но мог пропустить

2021-01-05 13:47 UTC, Kiep13 commented on package.json
>      "**/{aura|lwc}/**": [
Это потому что она внутренность удалила, поэтому он пометился. По идее сами эти строки должны быть

2021-01-05 14:13 UTC, DunaevViktor commented on force-app/main/default/lwc/singleTriggerRule/singleTriggerRule.html
> +    <!--Object-->
Кстати о комментах, Алексей говорил, что в итоговом коде - коменты это норм
даже функции норм описывать и тд, а тут для удобности чтения разметки
лично я думаю, что это ок

2021-01-06 10:20 UTC, Kiep13 commented on force-app/main/default/classes/MetadataFetcher.cls
> +      if (datatype == 'REFERENCE') {
Лучше бы 'REFERENCE' был статиком. Так, на будущее

2021-01-06 10:21 UTC, Kiep13 commented on force-app/main/default/classes/MetadataFetcherTest.cls
> +        'Undefined'
Обычные строки тоже лучше было бы вынести в статик

2021-01-06 10:21 UTC, julia018 commented on force-app/main/default/classes/MetadataFetcher.cls
> +      if (datatype == 'REFERENCE') {
константой?

2021-01-06 10:23 UTC, DunaevViktor approved these changes
Следующий раз добавляй пожалуйста скрины в описание пр, чтобы можно было подробнее посмотреть верстку lwc

2021-01-06 10:26 UTC, Kiep13 approved these changes

2021-01-06 11:24 UTC, merged